// <auto-generated />
using System;
using GPMS.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GPMS.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250913153335_added Reply Table with constraints")]
    partial class addedReplyTablewithconstraints
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GPMS.Models.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<long?>("SupervisorId")
                        .HasColumnType("bigint");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SupervisorId");

                    b.HasIndex("TaskId");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("GPMS.Models.KanbanTask", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<long>("SupervisorId")
                        .HasColumnType("bigint");

                    b.Property<long>("TeamId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("TaskId");

                    b.HasIndex("SupervisorId");

                    b.HasIndex("TeamId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("GPMS.Models.Link", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("Links");
                });

            modelBuilder.Entity("GPMS.Models.Project", b =>
                {
                    b.Property<string>("ProjectTitle")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectId"));

                    b.Property<long>("TeamId")
                        .HasColumnType("bigint");

                    b.Property<bool>("projectStatus")
                        .HasColumnType("bit");

                    b.HasKey("ProjectTitle");

                    b.HasIndex("TeamId")
                        .IsUnique();

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("GPMS.Models.Reply", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("FeedbackId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("StudentId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SupervisorId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FeedbackId");

                    b.HasIndex("StudentId");

                    b.HasIndex("SupervisorId");

                    b.ToTable("Replys");
                });

            modelBuilder.Entity("GPMS.Models.Student", b =>
                {
                    b.Property<long>("StudentId")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<long?>("TeamId")
                        .HasColumnType("bigint");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.HasKey("StudentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("TeamId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("GPMS.Models.StudentTask", b =>
                {
                    b.Property<long>("StudentId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    b.Property<int>("TaskId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StudentId", "TaskId");

                    b.HasIndex("TaskId");

                    b.ToTable("StudentTasks");
                });

            modelBuilder.Entity("GPMS.Models.Supervisor", b =>
                {
                    b.Property<long>("SupervisorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SupervisorId"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("VARCHAR(15)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("SupervisorId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Supervisors");
                });

            modelBuilder.Entity("GPMS.Models.Team", b =>
                {
                    b.Property<long>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TeamId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("SupervisorId")
                        .HasColumnType("bigint");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("TeamId");

                    b.HasIndex("SupervisorId");

                    b.HasIndex("TeamName")
                        .IsUnique();

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("GPMS.Models.Feedback", b =>
                {
                    b.HasOne("GPMS.Models.Supervisor", "Supervisor")
                        .WithMany("Feedbacks")
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GPMS.Models.KanbanTask", "KanbanTask")
                        .WithMany("Feedbacks")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KanbanTask");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("GPMS.Models.KanbanTask", b =>
                {
                    b.HasOne("GPMS.Models.Supervisor", "Supervisor")
                        .WithMany()
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GPMS.Models.Team", "Team")
                        .WithMany("KanbanTasks")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supervisor");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("GPMS.Models.Link", b =>
                {
                    b.HasOne("GPMS.Models.KanbanTask", "KanbanTask")
                        .WithMany("Links")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KanbanTask");
                });

            modelBuilder.Entity("GPMS.Models.Project", b =>
                {
                    b.HasOne("GPMS.Models.Team", "Team")
                        .WithOne("Project")
                        .HasForeignKey("GPMS.Models.Project", "TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("GPMS.Models.Reply", b =>
                {
                    b.HasOne("GPMS.Models.Feedback", "Feedback")
                        .WithMany("Replys")
                        .HasForeignKey("FeedbackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GPMS.Models.Student", "Student")
                        .WithMany("Replys")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GPMS.Models.Supervisor", "Supervisor")
                        .WithMany("Replys")
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Feedback");

                    b.Navigation("Student");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("GPMS.Models.Student", b =>
                {
                    b.HasOne("GPMS.Models.Team", "Team")
                        .WithMany("Students")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Team");
                });

            modelBuilder.Entity("GPMS.Models.StudentTask", b =>
                {
                    b.HasOne("GPMS.Models.Student", "Student")
                        .WithMany("StudentTask")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GPMS.Models.KanbanTask", "Task")
                        .WithMany("StudentTasks")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("GPMS.Models.Team", b =>
                {
                    b.HasOne("GPMS.Models.Supervisor", "Supervisor")
                        .WithMany("Teams")
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("GPMS.Models.Feedback", b =>
                {
                    b.Navigation("Replys");
                });

            modelBuilder.Entity("GPMS.Models.KanbanTask", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("Links");

                    b.Navigation("StudentTasks");
                });

            modelBuilder.Entity("GPMS.Models.Student", b =>
                {
                    b.Navigation("Replys");

                    b.Navigation("StudentTask");
                });

            modelBuilder.Entity("GPMS.Models.Supervisor", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("Replys");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("GPMS.Models.Team", b =>
                {
                    b.Navigation("KanbanTasks");

                    b.Navigation("Project");

                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
